security:
    enable_authenticator_manager: true
    encoders:
        App\Domain\User\Adapters\Gateway\Doctrine\ProjectHolder:
            algorithm: plaintext

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: App\Domain\User\Adapters\Gateway\Doctrine\ProjectHolder
                property: email
        app_user_provider_to:
            entity:
                class: App\Domain\User\Adapters\Gateway\Doctrine\Contributor
                property: email

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            provider: app_user_provider
            stateless: true
            jwt: ~



    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
